import { Router, type IRouter } from "express";
import { getAuth } from "@clerk/express";
import { eq, and } from "drizzle-orm";
import { db, invoicesTable, usersTable, teacherProfilesTable } from "@workspace/db";
import { requireAuth } from "../middlewares/requireAuth";
import { logger } from "../lib/logger";
import { isProSubscriber } from "./subscriptions";

const router: IRouter = Router();

function generateInvoiceHtml(
  invoice: typeof invoicesTable.$inferSelect,
  teacherName: string,
): string {
  const lineItems = (invoice.lineItems ?? []) as Array<{ description: string; amountInCents: number }>;
  const total = lineItems.length > 0
    ? lineItems.reduce((s, i) => s + i.amountInCents, 0)
    : invoice.amountInCents;

  const lineItemsHtml = lineItems.length > 0
    ? lineItems.map(li => `
      <tr>
        <td style="padding:10px;border-bottom:1px solid #e5e5d0;">${li.description}</td>
        <td style="padding:10px;border-bottom:1px solid #e5e5d0;text-align:right;">$${(li.amountInCents / 100).toFixed(2)}</td>
      </tr>`).join("")
    : `<tr><td style="padding:10px;">Services</td><td style="padding:10px;text-align:right;">$${(invoice.amountInCents / 100).toFixed(2)}</td></tr>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Invoice #${invoice.id}</title>
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; border-bottom: 3px solid #b8860b; padding-bottom: 20px; }
  .company { font-size: 24px; font-weight: bold; color: #b8860b; font-family: Georgia, serif; }
  .invoice-number { text-align: right; }
  .invoice-number h2 { font-size: 28px; margin: 0; color: #b8860b; }
  .invoice-number p { margin: 4px 0; color: #666; font-size: 13px; }
  .bill-section { display: flex; justify-content: space-between; margin-bottom: 30px; }
  .bill-to h4, .bill-from h4 { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #999; margin-bottom: 6px; }
  .bill-to p, .bill-from p { margin: 2px 0; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  thead tr { background: #b8860b; color: white; }
  thead td { padding: 12px 10px; font-size: 13px; font-weight: bold; }
  tbody tr:hover { background: #fafaf5; }
  .total-row td { padding: 14px 10px; font-size: 16px; font-weight: bold; border-top: 2px solid #b8860b; }
  .notes { background: #fafaf5; border: 1px solid #e5e5d0; border-radius: 6px; padding: 16px; margin-top: 20px; font-size: 13px; }
  .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; background: ${invoice.status === "paid" ? "#dcfce7" : invoice.status === "sent" ? "#dbeafe" : "#f3f4f6"}; color: ${invoice.status === "paid" ? "#16a34a" : invoice.status === "sent" ? "#2563eb" : "#6b7280"}; }
  @media print { body { margin: 10px; } }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="company">Harmonia</div>
    <p style="margin:4px 0;color:#666;font-size:13px;">${teacherName}</p>
  </div>
  <div class="invoice-number">
    <h2>INVOICE</h2>
    <p>#${String(invoice.id).padStart(4, "0")}</p>
    <p>Date: ${new Date(invoice.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
    ${invoice.dueDate ? `<p>Due: ${new Date(invoice.dueDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>` : ""}
    <span class="status-badge">${invoice.status.toUpperCase()}</span>
  </div>
</div>

<div class="bill-section">
  <div class="bill-from">
    <h4>From</h4>
    <p><strong>${teacherName}</strong></p>
  </div>
  <div class="bill-to">
    <h4>Bill To</h4>
    <p><strong>${invoice.clientName}</strong></p>
    <p>${invoice.clientEmail}</p>
  </div>
</div>

<table>
  <thead>
    <tr>
      <td>Description</td>
      <td style="text-align:right;">Amount</td>
    </tr>
  </thead>
  <tbody>
    ${lineItemsHtml}
  </tbody>
  <tfoot>
    <tr class="total-row">
      <td>Total (${invoice.currency})</td>
      <td style="text-align:right;">$${(total / 100).toFixed(2)}</td>
    </tr>
  </tfoot>
</table>

${invoice.paymentNote ? `<div class="notes"><strong>Payment Instructions:</strong><br>${invoice.paymentNote}</div>` : ""}
${invoice.notes ? `<div class="notes" style="margin-top:10px;"><strong>Notes:</strong><br>${invoice.notes}</div>` : ""}

<p style="font-size:12px;color:#999;margin-top:40px;">Generated by Harmonia Business Suite</p>
</body>
</html>`;
}

router.get("/invoices", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;

  if (!await isProSubscriber(userId)) {
    res.status(403).json({ error: "Business Suite subscription required" });
    return;
  }

  const invoices = await db
    .select()
    .from(invoicesTable)
    .where(eq(invoicesTable.teacherId, userId))
    .orderBy(invoicesTable.createdAt);

  res.json({ invoices });
});

router.post("/invoices", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;

  if (!await isProSubscriber(userId)) {
    res.status(403).json({ error: "Business Suite subscription required" });
    return;
  }

  const { clientEmail, clientName, amountInCents, currency, notes, paymentNote, lineItems, dueDate, bookingId } = req.body as {
    clientEmail: string;
    clientName: string;
    amountInCents?: number;
    currency?: string;
    notes?: string;
    paymentNote?: string;
    lineItems?: Array<{ description: string; amountInCents: number }>;
    dueDate?: string;
    bookingId?: number;
  };

  if (!clientEmail || !clientName) {
    res.status(400).json({ error: "clientEmail and clientName are required" });
    return;
  }

  const resolvedLineItems = lineItems ?? [];
  const resolvedAmount = resolvedLineItems.length > 0
    ? resolvedLineItems.reduce((s, i) => s + i.amountInCents, 0)
    : (amountInCents ?? 0);

  if (resolvedAmount <= 0) {
    res.status(400).json({ error: "amountInCents or lineItems with a positive total are required" });
    return;
  }

  const [invoice] = await db
    .insert(invoicesTable)
    .values({
      teacherId: userId,
      bookingId: bookingId ?? null,
      clientEmail,
      clientName,
      amountInCents: resolvedAmount,
      currency: currency ?? "USD",
      notes,
      paymentNote,
      lineItems: resolvedLineItems,
      dueDate: dueDate ? new Date(dueDate) : null,
      status: "draft",
    })
    .returning();

  res.status(201).json({ invoice });
});

router.get("/invoices/:id", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) { res.status(400).json({ error: "Invalid id" }); return; }

  const [invoice] = await db
    .select()
    .from(invoicesTable)
    .where(and(eq(invoicesTable.id, id), eq(invoicesTable.teacherId, userId)));

  if (!invoice) { res.status(404).json({ error: "Invoice not found" }); return; }

  res.json({ invoice });
});

router.patch("/invoices/:id", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) { res.status(400).json({ error: "Invalid id" }); return; }

  const { status, notes, paymentNote } = req.body as { status?: "draft" | "sent" | "paid"; notes?: string; paymentNote?: string };

  const extra: Record<string, unknown> = {};
  if (status === "sent") extra.sentAt = new Date();

  const [updated] = await db
    .update(invoicesTable)
    .set({
      ...(status !== undefined ? { status } : {}),
      ...(notes !== undefined ? { notes } : {}),
      ...(paymentNote !== undefined ? { paymentNote } : {}),
      ...extra,
      updatedAt: new Date(),
    })
    .where(and(eq(invoicesTable.id, id), eq(invoicesTable.teacherId, userId)))
    .returning();

  if (!updated) { res.status(404).json({ error: "Invoice not found" }); return; }

  res.json({ invoice: updated });
});

router.delete("/invoices/:id", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) { res.status(400).json({ error: "Invalid id" }); return; }

  await db
    .delete(invoicesTable)
    .where(and(eq(invoicesTable.id, id), eq(invoicesTable.teacherId, userId)));

  res.status(204).end();
});

router.post("/invoices/:id/send", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) { res.status(400).json({ error: "Invalid id" }); return; }

  if (!await isProSubscriber(userId)) {
    res.status(403).json({ error: "Business Suite subscription required" });
    return;
  }

  const [invoice] = await db
    .select()
    .from(invoicesTable)
    .where(and(eq(invoicesTable.id, id), eq(invoicesTable.teacherId, userId)));

  if (!invoice) { res.status(404).json({ error: "Invoice not found" }); return; }

  const [updated] = await db
    .update(invoicesTable)
    .set({ status: "sent", sentAt: new Date(), updatedAt: new Date() })
    .where(eq(invoicesTable.id, id))
    .returning();

  logger.info({ invoiceId: id, clientEmail: invoice.clientEmail }, "[NOTIFICATION] Invoice sent to client — email with PDF link");

  res.json({ invoice: updated, message: `Invoice marked as sent to ${invoice.clientEmail}` });
});

router.get("/invoices/:id/pdf", requireAuth, async (req, res): Promise<void> => {
  const auth = getAuth(req);
  const userId = auth.userId!;
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) { res.status(400).json({ error: "Invalid id" }); return; }

  const [[invoice], [teacherRow]] = await Promise.all([
    db.select().from(invoicesTable).where(and(eq(invoicesTable.id, id), eq(invoicesTable.teacherId, userId))),
    db.select({ firstName: usersTable.firstName, lastName: usersTable.lastName }).from(usersTable).where(eq(usersTable.id, userId)),
  ]);

  if (!invoice) { res.status(404).json({ error: "Invoice not found" }); return; }

  const teacherName = [teacherRow?.firstName, teacherRow?.lastName].filter(Boolean).join(" ") || "Teacher";
  const html = generateInvoiceHtml(invoice, teacherName);
  res.setHeader("Content-Type", "text/html");
  res.send(html);
});

export default router;
